# Generated by Django 5.2.1 on 2025-06-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attend',
            old_name='attended',
            new_name='user',
        ),
    ]
